import React from 'react';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PdfProvider } from "./contexts/PdfContext";
import { DownloadDialogProvider } from "./contexts/DownloadDialogContext";
import DownloadDialog from "@/components/shared/DownloadDialog";
import Navbar from "@/components/shared/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PdfProvider>
          <DownloadDialogProvider>
            <Navbar />
            {children}
            <DownloadDialog />
          </DownloadDialogProvider>
        </PdfProvider>
      </body>
    </html>
  );
}
